### ISSUE TITLE
Typo in example in README.rst

### ISSUE THREAD

**Issue by tessa-kramer** [vandersat/vds-api-client#6]
There is a typo in line 292 in README.rst. It says vds.submit_asynch_requests(), where it should be vds.submit_async_requests(). I tried to fix it myself, but I couldn't manage to push my changes.

**Comment by teije01** [comment]
Hi Tessa,
By default you can never push to master, that is a failsafe (in any project that is not your own). You have to submit a merge request (for which you need access to the VanderSat github as developer), or you need to fork a project, make changes and make a pull request.

Luckily, there is already a merge request open with the fix for this issue, so no need to do it again. I was still waiting to push these with other changes, but since you're not the first to notice I will do that now
